import type { LessonResult, PretestChoice, Polarity } from '$lib/lesson/schema';
import { fixture as lossMidMistake14m } from './loss_mid_mistake_14m';
import { fixture as winLateStrength22m } from './win_late_strength_22m';
import { fixture as nothingToTeach } from './nothing_to_teach_early_stomp';
import { fixture as lossProseMissing } from './loss_prose_missing_ambiguous';

/**
 * Everything that a fixture carries beyond what lives in the Python
 * LessonResult dataclass. Pretest choices, cohort prose, and intervention
 * suggestions will eventually be generated by the decision-diff pipeline
 * (bead 9b01bf83-8hi → 9b01bf83-dcy / 9b01bf83-b8n). Today they're hand
 * authored per fixture so stakeholders can walk the flow end to end.
 */
export interface FixtureExtras {
	cohortProse: string | null;
	pretestChoices: PretestChoice[];
	interventionSuggestions: string[];
}

export interface LessonFixture {
	id: string;
	summary: string;
	lesson: LessonResult;
	extras: FixtureExtras;
}

const fixtures: LessonFixture[] = [
	lossMidMistake14m,
	winLateStrength22m,
	nothingToTeach,
	lossProseMissing,
];

const byId = new Map(fixtures.map((f) => [f.id, f] as const));

export function getFixture(id: string): LessonFixture | undefined {
	return byId.get(id);
}

export interface FixtureSummary {
	id: string;
	summary: string;
	polarity: Polarity | 'neutral';
}

export const fixtureSummaries: FixtureSummary[] = fixtures.map((f) => ({
	id: f.id,
	summary: f.summary,
	polarity:
		(f.lesson.mistake_anchor?.polarity ??
			f.lesson.strength_anchor?.polarity ??
			'neutral') as Polarity | 'neutral',
}));
