<svelte:head>
	<title>Terms of Service — howtowin.lol</title>
	<meta name="description" content="Terms of Service for howtowin.lol." />
</svelte:head>

<article class="legal-page">
	<h1>Terms of Service</h1>
	<p class="meta">Last updated: 2026-04-18</p>

	<section>
		<h2>1. Acceptance</h2>
		<p>
			By accessing howtowin.lol ("the Service"), you agree to these Terms of Service. If
			you do not agree, do not use the Service.
		</p>
	</section>

	<section>
		<h2>2. What the Service does</h2>
		<p>
			howtowin.lol is a post-game coaching tool for League of Legends. It reads publicly
			available match data from the Riot Games API and produces lessons intended to help
			players improve.
		</p>
	</section>

	<section>
		<h2>3. Eligibility</h2>
		<p>
			You must be at least 13 years old to use the Service (or the minimum age required by
			your local law, whichever is higher). You must agree to, and comply with, the
			<a
				href="https://www.riotgames.com/en/terms-of-service"
				target="_blank"
				rel="noopener noreferrer">Riot Games Terms of Service</a
			>
			while using the Service.
		</p>
	</section>

	<section>
		<h2>4. Acceptable use</h2>
		<ul>
			<li>Do not use the Service to harass, dox, or target other players.</li>
			<li>Do not scrape, mirror, or resell data obtained through the Service.</li>
			<li>Do not use the Service to facilitate cheating, boosting, or account sharing.</li>
			<li>
				Do not attempt to reverse-engineer, overload, or circumvent rate limits on the
				Service or the underlying Riot API.
			</li>
		</ul>
	</section>

	<section>
		<h2>5. Riot Games disclaimer</h2>
		<p>
			howtowin.lol isn't endorsed by Riot Games and doesn't reflect the views or opinions
			of Riot Games or anyone officially involved in producing or managing League of
			Legends. League of Legends and Riot Games are trademarks or registered trademarks of
			Riot Games, Inc. League of Legends © Riot Games, Inc.
		</p>
	</section>

	<section>
		<h2>6. No warranty</h2>
		<p>
			The Service is provided "as is", without warranty of any kind. Coaching output is
			generated by machine-learning models and may be incomplete, outdated, or incorrect.
			Do not treat it as professional advice.
		</p>
	</section>

	<section>
		<h2>7. Limitation of liability</h2>
		<p>
			To the fullest extent permitted by law, the operators of howtowin.lol are not liable
			for any indirect, incidental, or consequential damages arising from your use of the
			Service.
		</p>
	</section>

	<section>
		<h2>8. Changes</h2>
		<p>
			We may update these terms. Material changes will be announced on this page with an
			updated revision date. Continued use after changes constitutes acceptance.
		</p>
	</section>

	<section>
		<h2>9. Contact</h2>
		<p>
			Questions or takedown requests: <a href="mailto:privacy@howtowin.lol">privacy@howtowin.lol</a>.
		</p>
	</section>
</article>

<style>
	.legal-page { max-width: 720px; display: flex; flex-direction: column; gap: 24px; }
	h1 { font-size: 1.8rem; margin-bottom: 4px; }
	.meta { color: var(--text-muted); font-size: 0.85rem; margin-top: -16px; }
	h2 { font-size: 1.05rem; margin-bottom: 8px; }
	p, li { color: var(--text-muted); line-height: 1.65; font-size: 0.95rem; }
	ul { padding-left: 20px; display: flex; flex-direction: column; gap: 6px; }
</style>
