#!/usr/local/env python3

import json
import cstat


#load json
f = open('../games/NA1_5032579472.timeline',)
game = json.load(f)

#get matchId
matchID = game['metadata']['matchId']

#get ID assignments
participantID = {}
for participantDto in game['info']['participants']:
	participantID[participantDto['participantId']]=participantDto['puuid']
	#write PUUIDs to database	
print(participantID)

#write db Files
db = {}
for playerID in participantID.keys():
	db[playerID] = {}
	db[playerID]['ITEMS'] = {0: 0}
	db[playerID]['ITEM_STATE']={0: 0}
	db[playerID]['DAMAGE'] = {}
	db[playerID]['WARDS'] = {}
	db[playerID]['BOUNTY'] = {}
	db[playerID]['OBJECTIVES'] = {}
	for dbStat in cstat.mvp_stats:
		db[playerID][dbStat] = {}
#build game row
with open('../DB/'+matchID+'_'+'info', 'w') as match_row:
	match_row.write(json.dumps(game['metadata']['matchId'])+'\n')
	match_row.write(json.dumps(game['info']['endOfGameResult'])+'\n')
	match_row.write(json.dumps(participantID)+'\n')

def handle_event(event):
	match event['type']:
		case "ITEM_UNDO":
			db[event['participantId']]['ITEMS'][event['timestamp']] = (event['afterId'], event['beforeId'])
			db[event['participantId']]['ITEM_STATE'][event['beforeId']] -=1
			db[event['participantId']]['ITEM_STATE'][event['afterId']] +=1
			db[event['participantId']]['ITEMS']['SET'+str(event['timestamp'])] = json.dumps(db[event['participantId']]['ITEM_STATE'])
			
			#db[event['participantId']]['GOLD']['timestamp'] =  #update gold totals
			#dict_keys(['afterId', 'beforeId', 'goldGain', 'participantId', 'timestamp', 'type'])
			return None
		case 'BUILDING_KILL':
			#update gold totals
			#dict_keys(['assistingParticipantIds', 'bounty', 'buildingType', 'killerId', 'laneType', 'position', 'teamId', 'timestamp', 'towerType', 'type']),
			return None
		case  'WARD_PLACED':
			#WARD_PLACED': dict_keys(['creatorId', 'timestamp', 'type', 'wardType']),
			return None
		case  'TURRET_PLATE_DESTROYED':
			#dict_keys(['killerId', 'laneType', 'position', 'teamId', 'timestamp', 'type']),
			return None
		case  'PAUSE_END':
			#pass
			return None
		case 'LEVEL_UP':
			#dict_keys(['level', 'participantId', 'timestamp', 'type'])
			return None
		case 'CHAMPION_SPECIAL_KILL':
			#dict_keys(['killType', 'killerId', 'position', 'timestamp', 'type']),
			return None
		case  'GAME_END':
			#(['gameId', 'realTimestamp', 'timestamp', 'type', 'winningTeam'])}
			return None
		case 'OBJECTIVE_BOUNTY_PRESTART':
			#dict_keys(['actualStartTime', 'teamId', 'timestamp', 'type']),
			return None
		case  'SKILL_LEVEL_UP':
			#dict_keys(['levelUpType', 'participantId', 'skillSlot', 'timestamp', 'type'])
			return None
		case 'ITEM_DESTROYED':
			db[event['participantId']]['ITEMS'][event['timestamp']] = event['itemId']
			#dict_keys(['itemId', 'participantId', 'timestamp', 'type'])
			return None
		case 'ITEM_PURCHASED':
			db[event['participantId']]['ITEMS'][event['timestamp']] = event['itemId']
			db[event['participantId']]['ITEM_STATE'].setdefault(event['itemId'], 0)
			db[event['participantId']]['ITEM_STATE'][event['itemId']] +=1
			db[event['participantId']]['ITEMS']['SET'+str(event['timestamp'])] = json.dumps(db[event['participantId']]['ITEM_STATE'])
			#'itemId', 'participantId', 'timestamp', 'type'
			return None
		case 'CHAMPION_KILL':
			#dict_keys(['assistingParticipantIds', 'bounty', 'killStreakLength', 'killerId', 'position', 'shutdownBounty', 'timestamp', 'type', 'victimDamageDealt', 'victimDamageReceived', 'victimId'])
			return None
		case 'ITEM_SOLD':
			#dict_keys(['itemId', 'participantId', 'timestamp', 'type']),
			return None
		case 'WARD_KILL':
			#dict_keys(['killerId', 'timestamp', 'type', 'wardType'])
			return None
		case 'ELITE_MONSTER_KILL':
			#dict_keys(['bounty', 'killerId', 'killerTeamId', 'monsterSubType', 'monsterType', 'position', 'timestamp', 'type']),
			return None
	assert False, "Unknown Event Type"
itemtypes={}

#build timeline rows
for index, frame in enumerate(game['info']['frames']):	
	#get events
	for event in frame['events']:
		#log event
		#print(event.keys())
		#print(event['type'])
		handle_event(event)
	for player in frame['participantFrames']:
		player_frame = frame['participantFrames'][player]
		#print(player_frame)
		for dbStat in ['currentGold', 'totalGold', 'xp']:
			stat = player_frame[dbStat]
			#print(str(stat))
			db[int(player)][dbStat][frame['timestamp']] = stat		

for playerID in db.keys():
	for dbStat in db[playerID].keys():
		with open(f'../DB/{matchID}_{participantID[playerID]}_{dbStat}', 'w') as buf:
			json.dump(db[playerID][dbStat], buf)

print(db[1])
