#!/usr/local/env python3

import json
import cstat

#load json
f = open('../games/NA1_5032579472.timeline',)
game = json.load(f)

#get matchId
matchID = game['metadata']['matchId']


#get assignment ID?

participantID = {}
for participantDto in game['info']['participants']:
	participantID[participantDto['participantId']]=participantDto['puuid']


#write db Files
db = {}
for dbStat in cstat.mvp_stats:
	for playerID in participantID.keys():
		db[dbStat] = open('../DB/'+matchID+'_'+participantID[int(playerID)]+'_'+dbStat, 'w')


#tasks:
#build out puuid database

#build gamedata rows
#build game row
# version, matchID, endOfGameResult, GameCreation, GameDuration, TrueGameEnd, gameID, gameMode, GameStartTimestamp, gameVersion, teams


#Should the game data be just included as a list of rows--no each datastream should be seperate.

#PlayerRow
#EOG statistics such as PingsCount, Assists, BaronKills and all other data in ParticipantDto. Indicate kayn transformation as null/0/1?
#ignore challenges, eligibleForProgression, doubleKills, 

#PingsRow


#ChampDataTable
#includes 

#ItemTable

#GoldTable

#

#The most reliable way of determining the timestamp for the end of the match would be to add the max time played of any participant to the gameStartTimestamp. 

#get all data for each player and load it into several vector series?

for index, frame in enumerate(game['info']['frames']):	
	#over all frames
	#separate each stat into its own file
	print(frame.keys())
	pFrame = frame['participantFrames']
	print(pFrame.keys())
	for playerID in pFrame.keys():
		#print(pFrame[playerID].keys())
		#print(pFrame[playerID])
		'''for dbStat in pFrame[playerID].keys():
			db[dbStat] = open('../DB/'+matchID+'_'+participantID[int(playerID)]+'_'+dbStat, 'w')
			stat = pFrame[playerID][dbStat]
			print(stat)
			db[dbStat].write(cstat.dump(stat))
		''' #Tabled for now to work on the MVP
		#MVP stats: Total Gold, Current Gold, item vector
		for dbStat in ['currentGold', 'totalGold', 'xp']:
			stat = pFrame[playerID][dbStat]
			print(stat)
			with open('../DB/'+matchID+'_'+participantID[int(playerID)]+'_'+dbStat, 'a') as db[dbStat]:
				db[dbStat].write(str(stat)+'\t')
	assert index <= 100

#MVP

#gold-normalised item WR
	#MVPMVP
	#1st item gold-normalised champ wr
	#(first full item)
	#build item wide-database
	#set codes?
	#statistical embedding?
	#items themselves are not important compared to stats?
	#possession of unique stats is independent of items...
	#question is, is it reversible? 
	#theoretically yes??? 
	#just store item vector
	#get item code for each?

#champ-normalised item WR
	#exists generally
#rune-normalised item WR


