#!/usr/bin/env python3
"""Prepare and optionally push checkpoints to a Hugging Face model repo via git-lfs.

The helper keeps credentials ephemeral:
- reads the token from HF_TOKEN (or HUGGINGFACE_HUB_TOKEN),
- never rewrites the remote URL to include the token,
- disables git credential helpers on clone/pull/push, and
- uses a temporary GIT_ASKPASS script so nothing is persisted to ~/.git-credentials.
"""

from __future__ import annotations

import argparse
import os
import shlex
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Iterable, Sequence

DEFAULT_TRACK_PATTERNS = ["*.pt", "*.pth", "*.ckpt", "*.bin", "*.safetensors"]
TOKEN_ENV_NAMES = ("HF_TOKEN", "HUGGINGFACE_HUB_TOKEN")


def fail(message: str) -> "None":
    raise SystemExit(f"error: {message}")


def echo_command(cmd: Sequence[object], cwd: Path | None = None) -> None:
    rendered = shlex.join(str(part) for part in cmd)
    if cwd is not None:
        print(f"+ (cd {shlex.quote(str(cwd))} && {rendered})")
    else:
        print(f"+ {rendered}")


def run(
    cmd: Sequence[object],
    *,
    cwd: Path | None = None,
    env: dict[str, str] | None = None,
    dry_run: bool = False,
    capture_output: bool = False,
    check: bool = True,
) -> subprocess.CompletedProcess[str]:
    echo_command(cmd, cwd=cwd)
    if dry_run:
        return subprocess.CompletedProcess([str(part) for part in cmd], 0, "", "")
    return subprocess.run(
        [str(part) for part in cmd],
        cwd=str(cwd) if cwd else None,
        env=env,
        text=True,
        check=check,
        capture_output=capture_output,
    )


class AskPassEnv:
    def __init__(self, token: str | None):
        self.token = token
        self._tempdir: tempfile.TemporaryDirectory[str] | None = None
        self.env: dict[str, str] | None = None

    def __enter__(self) -> dict[str, str]:
        env = os.environ.copy()
        env["GIT_TERMINAL_PROMPT"] = "0"
        env["GIT_LFS_SKIP_SMUDGE"] = "1"
        if self.token:
            self._tempdir = tempfile.TemporaryDirectory(prefix="howtowin-hf-askpass-")
            script_path = Path(self._tempdir.name) / "git-askpass.sh"
            script_path.write_text(
                "#!/usr/bin/env bash\n"
                "set -euo pipefail\n"
                "prompt=\"${1:-}\"\n"
                "case \"$prompt\" in\n"
                "  *Username*|*username*) printf '%s\\n' '__token__' ;;\n"
                "  *Password*|*password*) printf '%s\\n' \"${HF_TOKEN:?set HF_TOKEN}\" ;;\n"
                "  *) exit 1 ;;\n"
                "esac\n",
                encoding="utf-8",
            )
            script_path.chmod(0o700)
            env["HF_TOKEN"] = self.token
            env["GIT_ASKPASS"] = str(script_path)
        self.env = env
        return env

    def __exit__(self, exc_type, exc, tb) -> None:
        if self._tempdir is not None:
            self._tempdir.cleanup()


def parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description=(
            "Stage checkpoint artifacts into a Hugging Face model repo clone using git-lfs, "
            "then optionally push with env-var auth."
        )
    )
    p.add_argument(
        "artifacts",
        nargs="+",
        help="Checkpoint or artifact files/directories to copy into the model repo clone.",
    )
    p.add_argument(
        "--repo",
        default=os.environ.get("HOWL_HF_MODEL_REPO"),
        help="HF model repo in owner/name form. Defaults to $HOWL_HF_MODEL_REPO.",
    )
    p.add_argument(
        "--worktree",
        type=Path,
        help="Persistent local clone path. Defaults to ~/.cache/howtowin/hf-model-repos/<owner>__<repo>.",
    )
    p.add_argument(
        "--dest-dir",
        default="checkpoints",
        help="Destination directory inside the HF model repo. Defaults to checkpoints.",
    )
    p.add_argument(
        "--branch",
        default="main",
        help="Branch to update inside the HF model repo. Defaults to main.",
    )
    p.add_argument(
        "--track",
        action="append",
        default=[],
        metavar="GLOB",
        help="Additional git-lfs glob to track. Repeat to add more patterns.",
    )
    p.add_argument(
        "--commit-message",
        help="Commit message to use. Defaults to an autogenerated checkpoint upload message.",
    )
    p.add_argument(
        "--skip-pull",
        action="store_true",
        help="Skip the pre-copy git pull --ff-only.",
    )
    p.add_argument(
        "--allow-dirty",
        action="store_true",
        help="Allow a cached HF repo clone that already has uncommitted changes.",
    )
    p.add_argument(
        "--push",
        action="store_true",
        help="Push after committing.",
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the planned git/copy actions without modifying anything.",
    )
    return p


def find_token() -> tuple[str | None, str | None]:
    for env_name in TOKEN_ENV_NAMES:
        value = os.environ.get(env_name)
        if value:
            return value, env_name
    return None, None


def default_worktree(repo: str) -> Path:
    cache_root = Path(os.environ.get("XDG_CACHE_HOME", Path.home() / ".cache"))
    return cache_root / "howtowin" / "hf-model-repos" / repo.replace("/", "__")


def ensure_commands(*, dry_run: bool) -> None:
    if dry_run:
        print("note: dry-run skipped git/git-lfs availability validation")
        return
    if shutil.which("git") is None:
        fail("git is required but not on PATH")
    lfs_check = subprocess.run(
        ["git", "lfs", "version"],
        text=True,
        capture_output=True,
        check=False,
    )
    if lfs_check.returncode != 0:
        fail(
            "git-lfs is required but unavailable. Install it first (for example: apt install -y git-lfs or pacman -S git-lfs)."
        )


def ensure_git_identity(worktree: Path, *, dry_run: bool) -> None:
    if dry_run:
        print("note: dry-run skipped git user.name/user.email validation")
        return
    for key in ("user.name", "user.email"):
        result = subprocess.run(
            ["git", "config", key],
            cwd=str(worktree),
            text=True,
            capture_output=True,
            check=False,
        )
        if result.returncode != 0 or not result.stdout.strip():
            fail(f"git {key} is not configured; set it before committing to the HF model repo")


def ensure_clean_worktree(worktree: Path, *, allow_dirty: bool, dry_run: bool) -> None:
    result = run(["git", "status", "--porcelain"], cwd=worktree, dry_run=dry_run, capture_output=True)
    if dry_run:
        return
    if result.stdout.strip() and not allow_dirty:
        fail(
            f"cached worktree {worktree} has uncommitted changes; commit/stash them or pass --allow-dirty intentionally"
        )


def ensure_clone(worktree: Path, repo: str, *, env: dict[str, str], dry_run: bool) -> None:
    remote_url = f"https://huggingface.co/{repo}"
    if worktree.exists():
        if not (worktree / ".git").exists():
            fail(f"worktree path exists but is not a git repo: {worktree}")
        return
    run(["mkdir", "-p", worktree.parent], dry_run=dry_run)
    run(
        ["git", "-c", "credential.helper=", "clone", remote_url, worktree],
        env=env,
        dry_run=dry_run,
    )


def git_ref_exists(worktree: Path, ref: str) -> bool:
    result = subprocess.run(
        ["git", "rev-parse", "--verify", ref],
        cwd=str(worktree),
        text=True,
        capture_output=True,
        check=False,
    )
    return result.returncode == 0


def remote_branch_exists(worktree: Path, branch: str, env: dict[str, str]) -> bool:
    result = subprocess.run(
        ["git", "-c", "credential.helper=", "ls-remote", "--exit-code", "--heads", "origin", branch],
        cwd=str(worktree),
        env=env,
        text=True,
        capture_output=True,
        check=False,
    )
    return result.returncode == 0


def ensure_branch(worktree: Path, branch: str, *, env: dict[str, str], dry_run: bool) -> None:
    if dry_run:
        print(f"note: would ensure branch {branch!r} exists and is checked out")
        return
    if git_ref_exists(worktree, branch):
        run(["git", "checkout", branch], cwd=worktree)
        return
    if remote_branch_exists(worktree, branch, env):
        run(["git", "checkout", "-b", branch, "--track", f"origin/{branch}"], cwd=worktree)
        return
    run(["git", "checkout", "-B", branch], cwd=worktree)


def install_lfs(worktree: Path, *, dry_run: bool) -> None:
    run(["git", "lfs", "install", "--local", "--skip-smudge"], cwd=worktree, dry_run=dry_run)


def pull_latest(worktree: Path, branch: str, *, env: dict[str, str], dry_run: bool) -> None:
    if dry_run:
        print(f"note: would pull origin/{branch} if it exists")
        return
    if remote_branch_exists(worktree, branch, env):
        run(
            ["git", "-c", "credential.helper=", "pull", "--ff-only", "origin", branch],
            cwd=worktree,
            env=env,
        )
    else:
        print(f"note: origin/{branch} does not exist yet; skipping pull")


def unique_patterns(patterns: Iterable[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for pattern in patterns:
        if pattern not in seen:
            out.append(pattern)
            seen.add(pattern)
    return out


def track_lfs_patterns(worktree: Path, patterns: Sequence[str], *, dry_run: bool) -> None:
    for pattern in patterns:
        run(["git", "lfs", "track", pattern], cwd=worktree, dry_run=dry_run)


def resolve_artifacts(raw_paths: Sequence[str]) -> list[Path]:
    artifacts: list[Path] = []
    for raw in raw_paths:
        path = Path(raw).expanduser().resolve()
        if not path.exists():
            fail(f"artifact not found: {raw}")
        artifacts.append(path)
    return artifacts


def destination_paths(artifacts: Sequence[Path], dest_root: Path) -> list[Path]:
    seen: dict[Path, Path] = {}
    out: list[Path] = []
    for artifact in artifacts:
        dest = dest_root / artifact.name
        other = seen.get(dest)
        if other is not None and other != artifact:
            fail(
                f"artifact name collision under {dest_root}: {artifact.name!r} from {artifact} and {other}; use separate runs or rename first"
            )
        seen[dest] = artifact
        out.append(dest)
    return out


def copy_artifact(src: Path, dest: Path, *, dry_run: bool) -> None:
    if src.is_dir():
        echo_command(["copytree", src, dest])
        if dry_run:
            return
        dest.mkdir(parents=True, exist_ok=True)
        for child in src.iterdir():
            copy_artifact(child, dest / child.name, dry_run=False)
        return
    echo_command(["cp", "-f", src, dest])
    if dry_run:
        return
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dest)


def relative_paths(paths: Sequence[Path], root: Path) -> list[str]:
    return [str(path.relative_to(root)) for path in paths]


def autogenerated_commit_message(artifacts: Sequence[Path]) -> str:
    names = [path.name for path in artifacts]
    if len(names) == 1:
        return f"Upload checkpoint: {names[0]}"
    if len(names) <= 3:
        return f"Upload checkpoints: {', '.join(names)}"
    return f"Upload {len(names)} artifacts: {', '.join(names[:3])}, ..."


def staged_changes_exist(worktree: Path, staged_paths: Sequence[str], *, dry_run: bool) -> bool:
    result = run(
        ["git", "diff", "--cached", "--name-only", "--", *staged_paths],
        cwd=worktree,
        dry_run=dry_run,
        capture_output=True,
    )
    if dry_run:
        return True
    return bool(result.stdout.strip())


def main() -> int:
    args = parser().parse_args()

    if not args.repo:
        fail("pass --repo owner/name or export HOWL_HF_MODEL_REPO")

    ensure_commands(dry_run=args.dry_run)
    artifacts = resolve_artifacts(args.artifacts)
    worktree = args.worktree.expanduser().resolve() if args.worktree else default_worktree(args.repo)
    dest_root = worktree / args.dest_dir

    token, token_source = find_token()
    if token is None and not args.dry_run:
        fail(f"set one of {', '.join(TOKEN_ENV_NAMES)} before running this helper")

    track_patterns = unique_patterns([*DEFAULT_TRACK_PATTERNS, *args.track])
    commit_message = args.commit_message or autogenerated_commit_message(artifacts)
    staged_destinations = destination_paths(artifacts, dest_root)

    print(f"repo:      {args.repo}")
    print(f"worktree:  {worktree}")
    print(f"dest dir:  {dest_root}")
    print(f"branch:    {args.branch}")
    print(f"artifacts: {', '.join(str(path) for path in artifacts)}")
    print(f"track:     {', '.join(track_patterns)}")
    if token_source:
        print(f"auth:      {token_source} via temporary askpass (not persisted)")
    elif args.dry_run:
        print("auth:      dry-run only (no token required)")

    with AskPassEnv(token) as auth_env:
        ensure_clone(worktree, args.repo, env=auth_env, dry_run=args.dry_run)
        ensure_clean_worktree(worktree, allow_dirty=args.allow_dirty, dry_run=args.dry_run)
        ensure_branch(worktree, args.branch, env=auth_env, dry_run=args.dry_run)
        if not args.skip_pull:
            pull_latest(worktree, args.branch, env=auth_env, dry_run=args.dry_run)
        ensure_git_identity(worktree, dry_run=args.dry_run)
        install_lfs(worktree, dry_run=args.dry_run)
        track_lfs_patterns(worktree, track_patterns, dry_run=args.dry_run)

        for src, dest in zip(artifacts, staged_destinations, strict=True):
            copy_artifact(src, dest, dry_run=args.dry_run)

        git_add_paths = [worktree / ".gitattributes", *staged_destinations]
        run(
            ["git", "add", "--", *relative_paths(git_add_paths, worktree)],
            cwd=worktree,
            dry_run=args.dry_run,
        )

        staged_paths = [".gitattributes", *relative_paths(staged_destinations, worktree)]
        if not staged_changes_exist(worktree, staged_paths, dry_run=args.dry_run):
            print("Nothing changed after staging; nothing to commit.")
            return 0

        run(["git", "commit", "-m", commit_message], cwd=worktree, dry_run=args.dry_run)
        if args.push:
            run(
                ["git", "-c", "credential.helper=", "push", "origin", "HEAD"],
                cwd=worktree,
                env=auth_env,
                dry_run=args.dry_run,
            )
            print("Done: committed and pushed to the Hugging Face model repo.")
        else:
            print("Done: committed locally. Re-run with --push when you want to publish the checkpoint.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
